# Global parameters
CONFIG_MAIN_STACK_SIZE=8192

# Format image for MCUBoot (header,trailer,TLV,...)
CONFIG_BOOTLOADER_MCUBOOT=y
# File path as of version 4.1.0, from 4.2.0 path is relative to the folder
CONFIG_MCUBOOT_SIGNATURE_KEY_FILE="updatebox/samples/zephyr/mcuboot_flash_img_copy/keys/root-rsa-2048.pem"
CONFIG_MCUBOOT_IMGTOOL_SIGN_VERSION="0.0.0+0"

# Minimal configuration for flashing
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y

# Enable reboot for updatebox
CONFIG_REBOOT=y

# Enable MCUBoot for updatebox
CONFIG_IMG_MANAGER=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
