# Sysbuild configuration file.

# Enable MCUboot per default for this sample.
SB_CONFIG_BOOTLOADER_MCUBOOT=y
# Path handling with zephyr 4.1.0 conflicting when it propagates to ninja so as intial build path is good but final path is wrong
# SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="updatebox/samples/zephyr/mcuboot_flash_img_copy/keys/root-rsa-2048.pem"
